### ISSUE TITLE
chapter 6.7 exists warning

### ISSUE THREAD

**Issue by sukai-cheng** [zhayujie/C-Primer-Plus#1]
**Warning**:Implicit conversion loses integer precision: 'unsigned long' to 'int'

![image](https://user-images.githubusercontent.com/35868545/64155209-effe9080-ce64-11e9-93cc-bf11dc91819a.png)

**Comment by sukai-cheng** [comment]
Pls check my code,thanks for your time~
**AC:**

```
#include <stdio.h>
#include <string.h>
#define WORD_SIZE 26
int main (void)
{
    char word[WORD_SIZE];
    printf("Input a word:\n");
    scanf("%s",word);
    for( long i = strlen(word);i >= 0; i--){
        printf("%c",word[i]);
    }
    printf("\n");
    return 0;
}
```

**Comment by zhayujie** [comment]
会有类型强转的warning，你的写法更规范，已修改，多谢指正。
PS: 以前的代码比较粗糙，仅供参考哈 ^_^
